// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cLOUkCXajELRGgSPtb4RAgO-7H1JQBU',
    appId: '1:955414687464:web:b8b87f91d6c69e0cbea35d',
    messagingSenderId: '955414687464',
    projectId: 'flutter-firebase-bdfcd',
    authDomain: 'flutter-firebase-bdfcd.firebaseapp.com',
    storageBucket: 'flutter-firebase-bdfcd.appspot.com',
    measurementId: 'G-EQM6LW9VZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIacOgJnM1c7_tr7KFcpEK_7T6Ug2KEvk',
    appId: '1:955414687464:android:ad8e7c9d38256136bea35d',
    messagingSenderId: '955414687464',
    projectId: 'flutter-firebase-bdfcd',
    storageBucket: 'flutter-firebase-bdfcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJNwCQejp7bzkgoiCYCrIA7Tx-nBFhemY',
    appId: '1:955414687464:ios:4c3ea9a2ca101f70bea35d',
    messagingSenderId: '955414687464',
    projectId: 'flutter-firebase-bdfcd',
    storageBucket: 'flutter-firebase-bdfcd.appspot.com',
    iosClientId: '955414687464-804vq0s8udee5gjmsvcjngl81p7tm0ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJNwCQejp7bzkgoiCYCrIA7Tx-nBFhemY',
    appId: '1:955414687464:ios:9face78f9fcb766bbea35d',
    messagingSenderId: '955414687464',
    projectId: 'flutter-firebase-bdfcd',
    storageBucket: 'flutter-firebase-bdfcd.appspot.com',
    iosClientId: '955414687464-unvp0e601786jpcstid0jgs7i21u8qcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
